realtor_helper/config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :agents
  resources :listings
    root 'welcome#index'
end

realtor_helper/app/models/agent.rb
class Agent < ActiveRecord::Base
has_many :listing , :dependent => :delete_all
end

realtor_helper/app/models/feature.rb
class Feature < ActiveRecord::Base
  has_and_belongs_to_many :listing
end

realtor_helper/app/models/listing.rb
class Listing < ActiveRecord::Base
belongs_to :agent
has_and_belongs_to_many :feature
  validates :hid, presence: true
  validates :address, presence: true
  validates :price, presence: true,
  :numericality => { :greater_than_or_equal_to => 0 }
  validates :description, presence: true
end

realtor_helper/app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    @agents = Agent.all
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit(:name, :phone, :email)
    end
end

realtor_helper/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

realtor_helper/app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: [:show, :edit, :update, :destroy]

  # GET /features
  # GET /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1
  # GET /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1
  # PATCH/PUT /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature.destroy
    respond_to do |format|
      format.html { redirect_to features_url, notice: 'Feature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feature_params
      params.require(:feature).permit(:name)
    end
end

realtor_helper/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def show
    @listing = Listing.find(params[:id])


  end

  def index
    @listings = Listing.all
  end

  def new
    @listing = Listing.new
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.agent = Agent.find(params[:agent_id])


    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.agent = Agent.find(params[:agent_id])

    @feat = params[:feature_id]
    if !@feat.nil?

      @feat.each do |feature|

        obj = Feature.find(feature.to_i)

        @listing.feature << obj.name

      end

    end

    if @listing.update(listing_params)
      redirect_to @listing
    else
      render 'edit'
    end
  end

  private
  def listing_params
    params.require(:listing).permit(:hid, :address , :price, :description, :agent_id, :feature_id=>[])
  end

end

realtor_helper/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

realtor_helper/app/helpers/agents_helper.rb
module AgentsHelper
end

realtor_helper/app/helpers/application_helper.rb
module ApplicationHelper
end

realtor_helper/app/helpers/features_helper.rb
module FeaturesHelper
end

realtor_helper/app/helpers/listings_helper.rb
module ListingsHelper
end

realtor_helper/app/helpers/welcome_helper.rb
module WelcomeHelper
end

realtor_helper/app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

realtor_helper/app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Agents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.name %></td>
        <td><%= agent.phone %></td>
        <td><%= agent.email %></td>
        <td><%= link_to 'Show', agent %></td>
        <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
        <td><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/agents/new.html.erb
<h1>New Agent</h1>

<%= render 'form' %>

<%= link_to 'Back', agents_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agent.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agent.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @agent.email %>
</p>

<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/features/_form.html.erb
<%= form_for(@feature) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

realtor_helper/app/views/features/edit.html.erb
<h1>Editing Feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @feature %> |
<%= link_to 'Back', features_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/features/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Features</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @features.each do |feature| %>
      <tr>
        <td><%= feature.name %></td>
        <td><%= link_to 'Show', feature %></td>
        <td><%= link_to 'Edit', edit_feature_path(feature) %></td>
        <td><%= link_to 'Destroy', feature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feature', new_feature_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/features/new.html.erb
<h1>New Feature</h1>

<%= render 'form' %>

<%= link_to 'Back', features_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feature.name %>
</p>

<%= link_to 'Edit', edit_feature_path(@feature) %> |
<%= link_to 'Back', features_path %> |
<%= link_to 'Home', root_path %>

realtor_helper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealtorHelper</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

realtor_helper/app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>

    <% if @listing.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@listing.errors.count, "error") %> prohibited
            this house from being saved:
          </h2>
          <ul>
            <% @listing.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :hid %><br>
      <%= f.text_field :hid %>
    </p>

    <p>
      <%= f.label :address %><br>
      <%= f.text_field :address %>
    </p>

    <p>
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </p>

    <p>
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <strong>Agents:</strong>
      <%= select_tag "agent_id",options_from_collection_for_select(Agent.all, "id", "name")%>
    </p>
    <strong>Features:</strong>
    <%= f.collection_check_boxes :feature_ids, Feature.all, :id, :name do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
    <% end %>

    <p>
      <%= f.submit %>
    </p>
<% end %>

realtor_helper/app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>
<%= link_to 'Home', root_path %>

realtor_helper/app/views/listings/index.html.erb
<h1>Listing Houses</h1>

<%= link_to 'Home', root_path %> |
<%= link_to 'Add House', new_listing_path %>


<table>
  <tr>
    <th>House ID</th>
    <th>Address</th>
    <th>Listing Price</th>
    <th colspan="4"></th>
  </tr>

  <% @listings.each do |house| %>
      <tr>
        <td><%= house.hid %></td>
        <td><%= house.address %></td>
        <td><%= house.price %></td>
        <td><%= link_to 'Show', listing_path(house) %></td>
        <td><%= link_to 'Edit', edit_listing_path(house) %></td>
      </tr>
  <% end %>
</table>

realtor_helper/app/views/listings/new.html.erb
<h1>Add New House</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>
<%= link_to 'Home', root_path %>

realtor_helper/app/views/listings/show.html.erb
<p>
  <strong>House Id:</strong>
  <%= @listing.hid %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Agent Information:</strong>
  <p>
    Name: <%= @listing.agent.name %>
  </p>
  <p>
    Email: <%= @listing.agent.email %>
  </p>
  <p>
    Phone: <%= @listing.agent.phone %>
  </p>
</p>

<p>
  <strong>Features:</strong>
  <% @listing.feature.each do | teacher | %>

      <%= teacher.nil? %>
  <% end %>
</p>

<%= @listing.feature.inspect%>

<%= link_to 'Back', listings_path %>
<%= link_to 'Home', root_path %>

realtor_helper/app/views/welcome/index.html.erb
<h1>Welcome to Mike's Realtor Helper</h1>
<%= link_to 'All Listings', controller: 'listings' %> |
<%= link_to 'All Agents', controller: 'agents' %> |
<%= link_to 'All Features', controller: 'features' %>